# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2cat < Formula
  desc "ec2cat is a command line tool to list and filter EC2 instances"
  homepage "https://github.com/the-exile-110/homebrew-ec2cat"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/the-exile-110/homebrew-ec2cat/releases/download/v0.0.3/ec2cat_Darwin_x86_64.tar.gz"
      sha256 "2f694b8989003bd89bb0c5c79dbbdb8ad29d3ad3585cef032ceaf34eea293ea5"

      def install
        bin.install "ec2cat"
      end
    end
    on_arm do
      url "https://github.com/the-exile-110/homebrew-ec2cat/releases/download/v0.0.3/ec2cat_Darwin_arm64.tar.gz"
      sha256 "5850c1e07b439c28411238c31107516e40fda7ae4343c85070f0d84901f6ddf3"

      def install
        bin.install "ec2cat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-exile-110/homebrew-ec2cat/releases/download/v0.0.3/ec2cat_Linux_x86_64.tar.gz"
        sha256 "09bd2ac6b402875f0a5a5d4416cecfe9c8fd19e5e8e284aa439e07d6dc7003bb"

        def install
          bin.install "ec2cat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-exile-110/homebrew-ec2cat/releases/download/v0.0.3/ec2cat_Linux_arm64.tar.gz"
        sha256 "9dec7edb73a77a08d0e021d2ae26763fe4fc00a71fd8a7f4ff3013c67c3dfc36"

        def install
          bin.install "ec2cat"
        end
      end
    end
  end
end
